plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nova.keyboard'
    compileSdk 36

    defaultConfig {
        applicationId 'com.nova.keyboard'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }
}
